/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2016-02-06 22:28:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Hello World</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"webproj1/resources/core/css/bootstrap.min.css\" />\r\n");
      out.write("<script src=\"webproj1/resources/core/js/jquery.1.10.2.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\" style=\"min-height: 500px\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"starter-template\">\r\n");
      out.write("\t\t<h1>Search Form</h1>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"feedback\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<form class=\"form-horizontal\" id=\"search-form\">\r\n");
      out.write("\t\t\t<div class=\"form-group form-group-lg\">\r\n");
      out.write("\t\t\t\t<label class=\"col-sm-2 control-label\">Username</label>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t<input type=text class=\"form-control\" id=\"username\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group form-group-lg\">\r\n");
      out.write("\t\t\t\t<label class=\"col-sm-2 control-label\">Email</label>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"email\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-offset-2 col-sm-10\">\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" id=\"bth-search\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-primary btn-lg\">Search</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tjQuery(document).ready(function($) {\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#search-form\").submit(function(event) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t// Disble the search button\r\n");
      out.write("\t\t\tenableSearchButton(false);\r\n");
      out.write("\r\n");
      out.write("\t\t\t// Prevent the form from submitting via the browser.\r\n");
      out.write("\t\t\tevent.preventDefault();\r\n");
      out.write("\r\n");
      out.write("\t\t\tsearchViaAjax();\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction searchViaAjax() {\r\n");
      out.write("\r\n");
      out.write("\t\tvar search = {}\r\n");
      out.write("\t\tsearch[\"username\"] = $(\"#username\").val();\r\n");
      out.write("\t\tsearch[\"email\"] = $(\"#email\").val();\r\n");
      out.write("\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tcontentType : \"application/json\",\r\n");
      out.write("\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${home}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("webproj1/search/api/getSearchResult\",\r\n");
      out.write("\t\t\tdata : JSON.stringify(search),\r\n");
      out.write("\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\ttimeout : 100000,\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tconsole.log(\"SUCCESS: \", data);\r\n");
      out.write("\t\t\t\tdisplay(data);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\tconsole.log(\"ERROR: \", e);\r\n");
      out.write("\t\t\t\tdisplay(e);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdone : function(e) {\r\n");
      out.write("\t\t\t\tconsole.log(\"DONE\");\r\n");
      out.write("\t\t\t\tenableSearchButton(true);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction enableSearchButton(flag) {\r\n");
      out.write("\t\t$(\"#btn-search\").prop(\"disabled\", flag);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction display(data) {\r\n");
      out.write("\t\tvar json = \"<h4>Ajax Response</h4><pre>\"\r\n");
      out.write("\t\t\t\t+ JSON.stringify(data, null, 4) + \"</pre>\";\r\n");
      out.write("\t\t$('#feedback').html(json);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
